# Generated by Django 6.0 on 2026-08-03 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='unlock_cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
