# Generated by Django 6.0 on 2026-08-03 09:52

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_unlock_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=8, unique=True, validators=[cars.models.validate_license_plate]),
        ),
    ]
