# Generated by Django 6.0 on 2026-08-04 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_available_car_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='battery_percentage',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
