# Generated by Django 6.0 on 2026-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='gateway_transaction_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='rental',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active / Unlocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
    ]
