# Generated by Django 6.0 on 2025-12-11 22:55

import cars.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=6, unique=True, validators=[cars.models.validate_license_plate])),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('doors', models.IntegerField(choices=[(3, '3 Doors'), (5, '5 Doors')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('range_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
