# Generated by Django 6.0 on 2026-07-17 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rental_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
