# Generated by Django 6.0 on 2026-08-03 09:52

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_unlock_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=8, unique=True, validators=[vehicles.models.validate_license_plate]),
        ),
    ]
