# Generated by Django 6.0 on 2026-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
