# Generated by Django 6.0 on 2026-08-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='locked',
            new_name='is_locked',
        ),
    ]
