# Generated by Django 6.0 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway_transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
